### ISSUE TITLE
Reports types.

### ISSUE THREAD

**Issue by miltlima** [pmd/pmd-github-action#169]
Hello Folks !!

Is there any way to specify the type of report in the action ? per example , can i do this 

``` yaml
 - uses: pmd/pmd-github-action@v1
      id: pmd
      with:
        version: '6.40.0'
        sourcePath: 'src/main/java'
        rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'
        reportFile: 'pmd-report.xlst' "Or another report file extension"
``` 

Thanks!
