### ISSUE TITLE
Clarify the need for Java

### ISSUE THREAD

**Issue by adangel** [pmd/pmd-github-action#31]
This action calls PMD and PMD requires a Java runtime for execution.
In the README.md the following basic configuration is suggested:

```yaml
steps:
  - uses: actions/setup-java@v2
    with:
      distribution: 'temurin'
      java-version: '11'
  - uses: pmd/pmd-github-action@v1
    with:
      rulesets: 'ruleset.xml'
```

However, the "actions/setup-java" step is not really necessary, since Java is one of the pre-installed tools in the runners. See https://github.com/actions/virtual-environments/ and more specifically https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#java 
This is available under all operating systems.
