### ISSUE TITLE
Resource not accessible when `analyzeModifiedFileOnly` is `true`

### ISSUE THREAD

**Issue by msche** [pmd/pmd-github-action#371]
When I run the github action with `analyzeModifiedFileOnly` to `true` I get the following error:

```
Run pmd/pmd-github-action@v2
  
/usr/bin/unzip -o -q /home/runner/work/_temp/734ad628-b1a7-4072-a326-fedfa14bd85e
Using PMD 7.[10](https://github.com/S1moneBV/S1moneApplication/actions/runs/13311467680/job/37174818720#step:4:10).0 from cached path /opt/hostedtoolcache/pmd/7.[10](https://github.com/S1moneBV/S1moneApplication/actions/runs/13311467680/job/37174818720#step:4:11).0/x64
Determining modified files in ....
Error: Resource not accessible by integration - https://docs.github.com/rest/pulls/pulls#list-pull-requests-files
```

**Comment by msche** [comment]
Found out why the action was failing. I didn't have right permission. By adding the following permissions, it started working:

```
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
```
